name: Verification Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  generate-admin-swagger-code:
    runs-on: ubuntu-latest
    name: Generate Admin Swagger Code
    needs: [ generate-protos ]
    container:
      image: lyft/protocgenerator:8167e11d3b3439373c2f033080a4b550078884a2
      options: --cpus 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: "Clean Generated"
        run: rm -rf ./gen
      - uses: actions/download-artifact@master
        with:
          name: generated
          path: ./gen
      - run: ls gen/pb-go/flyteidl/service/
      - run: cp -R gen/pb-go/flyteidl/service/ ../
      - run: ls ../service/
      # Open API 2
      - name: OpenAPI-Binary
        run: go-bindata -pkg service -o ../service/openapi.go -prefix ../service/ -modtime 1562572800 ../service/admin.swagger.json
      - run: rm -rf gen/pb-go/flyteidl/service
      - run: mkdir -p gen/pb-go/flyteidl/service
      - run: cp -R ../service gen/pb-go/flyteidl/
      - run: ls gen/pb-go/flyteidl/
      - run: ls gen/pb-go/flyteidl/service/
      - uses: actions/upload-artifact@master
        with:
          name: generated
          path: ./gen

  generate-swagger-code:
    runs-on: ubuntu-latest
    name: Generate Swagger Code
    needs: [ generate-js-code ]
    container:
      image: docker.io/lyft/swagger-codegen-cli:dc5ce6ec6d7d4d980fa882d6bd13a83cba3be3c3
      options: --cpus 1
      volumes:
        - /github/workspace:/defs
      env:
        REPO_BLOB_SHA: master
        PROJECT_ANNOTATION_PREFIX: flyte.interface
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: "Clean Generated"
        run: rm -rf ./gen
      - uses: actions/download-artifact@master
        with:
          name: generated
          path: ./gen
      - run: java -jar /opt/swagger-codegen-cli/swagger-codegen-cli.jar generate -i ./gen/pb-go/flyteidl/service/admin.swagger.json -l go -o ./gen/pb-go/flyteidl/service/flyteadmin --additional-properties=packageName=flyteadmin
      - run: java -jar /opt/swagger-codegen-cli/swagger-codegen-cli.jar generate -i ./gen/pb-go/flyteidl/service/admin.swagger.json -l python -o ./gen/pb_python/flyteidl/service/flyteadmin --additional-properties=packageName=flyteadmin
      - uses: actions/upload-artifact@master
        with:
          name: generated
          path: ./gen
